source 'https://rubygems.org'

gem 'rails', '4.2.6'

gem 'rails-api'

gem 'spring', group: :development

gem 'mysql2', '~> 0.3.20'

gem 'active_model_serializers', '~> 0.8.3'

group :development, :test do
  gem 'lol_dba'
  gem 'metric_fu'
  gem 'rspec-rails'
  gem 'awesome_print'
  gem 'gemsurance'
  gem 'brakeman'
end

group :test do
  gem 'simplecov'
  gem 'json'
  gem 'factory_girl_rails'
end
